---
- name: Cisco IOS Upgrade playbook
  hosts: routers
  gather_facts: false
  become: yes

  tasks:
    - name: IOS Gather facts
      include_tasks: tasks/ios/cisco_ios_gather_facts.yml

    - name: Identifying the model facts
      set_fact:
        device: "{{ ansible_facts.net_model | lower }}"
    
    - name: Load device variables
      include_vars: vars/{{device}}.yml

    - name: Check Free Space
      include_tasks: tasks/ios/cisco_ios_check_free_space.yml

    - name: 'Copy software image'
      include_tasks: tasks/common/cisco_image_status.yml

    - name: Initiate Pre Check
      include_tasks: tasks/common/ios_pre_post_check.yml
      vars:
        log_type: pre

    - name: Change Boot Variable to new image 
      ios_config: 
        commands: 
          - "no boot system"
        save_when: always 

    - name: Change Boot Variable to new image 
      ios_config: 
        commands: 
          - "boot system flash {{ios_image}}"
        save_when: always 

    # - name: Initiate Reload
    #   include_tasks: tasks/ios/cisco_ios_reload.yml

    # # - name: Wait for device to come back online
    # #   wait_for:
    # #     host: "{{ inventory_hostname }}"
    # #     port: 22
    # #     delay: 60
    # #     timeout: 300

    # # - name: Reset connection
    # #   meta: reset_connection

    - name: Initiate Post Check
      include_tasks: tasks/common/ios_pre_post_check.yml
      vars:
        log_type: post

    - name: Compare Pre Post Data
      include_tasks: tasks/common/ios_pre_post_comparison.yml