- name: "{{log_type}}: Get cisco_ios_sh_ip_int_bri_check"
  ios_command:
    commands:
      - show ip int bri
  register: cmd_var
  ignore_errors: True

- set_fact:
    output: "{{cmd_var.stdout_lines | to_yaml}}"

- name: "{{log_type}}: filtering cisco_ios_sh_ip_int_bri_check output"
  set_fact: 
    fil_cisco_ios_sh_ip_int_bri_check_{{log_type}}: "{{output | filter_sh_ip_int_bri}}"
  when: cmd_var.failed != true